### ISSUE TITLE
Add PLL to improve the camera pixels input.

### ISSUE THREAD

**Issue by jordonezcerezo** [JdeRobot/FPGA-robotics#19]
SB_PLL40_CORE #(
        .FEEDBACK_PATH("PHASE_AND_DELAY"),
        .DELAY_ADJUSTMENT_MODE_FEEDBACK("FIXED"),
        .DELAY_ADJUSTMENT_MODE_RELATIVE("FIXED"),
        .PLLOUT_SELECT("SHIFTREG_0deg"),
        .SHIFTREG_DIV_MODE(1'b0),
        .FDA_FEEDBACK(4'b0000),
        .FDA_RELATIVE(4'b0000),
        .DIVR(4'b0000),
        .DIVF(7'd1), // frecuency multiplier = 1 + 1 = 2; 2 * 12 = 24 MHz
        .DIVQ(3'd3),
        .FILTER_RANGE(3'b001),
    ) pll1 (
        .REFERENCECLK   (CLK),       // clk entrada
        .PLLOUTGLOBAL   (outClk),  // clock salida
        .BYPASS         (1'b0),      // ?
        .RESETB         (1'b1)       // Reset se puede controlar, activo con 0
        //.LOCK (LOCK )              // lock es de salida e indica si el pll esta funcionando (frequency locked)
    );

**Comment by felipe-m** [comment]
closed by #44
