### ISSUE TITLE
Object Detection with OV7670 Camera 

### ISSUE THREAD

**Issue by Javi-Garci** [JdeRobot/FPGA-robotics#71]
This project consists of the detection of objects applying their corresponding color filter using the OV7670 camera and  Alhambra II.

**Comment by felipe-m** [comment]
pull request #72

**Comment by Javi-Garci** [comment]
The same project but adapted to the Nexys 4 DDR board. In this case, all the data pins of the camera are used because this FPGA has a greater number of pins than the Alhambra II.

**Comment by felipe-m** [comment]
#99 closes his issue
